version : '3.8'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - apps/web/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.web
    ports:
      - 3002:3000
    env_file:
      - apps/web/.env
    depends_on:
      postgres:
        condition: service_healthy
  
volumes:
  postgres_data: